spring.application.name=secure-demo

spring.datasource.url=jdbc:h2:mem:securedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Nunca exponer trazas de error detalladas al cliente
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

# H2 console deshabilitada por defecto (superficie de ataque innecesaria en produccion)
spring.h2.console.enabled=false
